(function(){
  const AR={
    header:{eyebrow:'تطوير رقمي مستقل · مصر',title:'أحمد محي — منتجات رقمية تساعد الأعمال على النمو',subtitle:'مواقع إلكترونية · تطبيقات ويب · متاجر إلكترونية · تطبيقات موبايل · تسويق رقمي',email:'راسلني',whatsapp:'واتساب',linkedin:'لينكدإن',github:'جيت هب',instagram:'إنستجرام'},
    build:{eyebrow:'ماذا أبني',title:'من الفكرة إلى الإطلاق — مواقع وتطبيقات ومتاجر وتسويق.',text:'حلول رقمية مستقلة للشركات الناشئة والمشروعات الصغيرة والعلامات التجارية المتنامية. أسعار واضحة وتصميم حديث وتطوير متجاوب ودعم حتى الإطلاق.',cta:'ابدأ مشروعك'},
    work:{eyebrow:'أعمال مختارة',title:'مشاريع حقيقية. واجهات حقيقية. مصممة لأعمال حقيقية.',intro:'مواقع حقيقية معروضة من خلال لقطات حديثة. افتح أي مشروع للدخول إلى الموقع الأصلي.',enter:'دخول إلى الموقع ↗',snapshot:'لقطة مباشرة للموقع',open:'فتح الموقع ↗'},
    pricing:{eyebrow:'أسعار العمل المستقل',title:'عمل احترافي بدون أسعار وكالات مرتفعة.',intro:'الأسعار المبدئية مصممة لتكون مناسبة للسوق المصري مع إمكانية إضافة المزايا المخصصة والمشروعات الأعلى تعقيدًا.',from:'ابتداءً من',month:'/شهريًا',popular:'الأكثر طلبًا',titles:['موقع أعمال','متجر إلكتروني','تطبيق ويب','نسخة أولية لتطبيق موبايل','صفحة هبوط لحملة','تسويق رقمي'],labels:['01 · موقع إلكتروني','02 · تجارة إلكترونية','03 · تطبيق ويب','04 · تطبيق موبايل','05 · صفحة هبوط','06 · تسويق رقمي'],desc:['للشركات والمستقلين والمحترفين ومقدمي الخدمات.','متاجر Shopify أو WooCommerce احترافية مصممة للبيع.','لوحات تحكم وأنظمة حجز وبوابات وأدوات أعمال مخصصة.','تطبيقات Android وiOS عملية لاختبار الفكرة وإطلاقها.','صفحات سريعة ومركزة للمنتجات والخدمات والحملات الإعلانية.','دعم تسويقي عملي يركز على الظهور وجذب العملاء وزيادة المبيعات.'],features:[['حتى 5 صفحات','تصميم متجاوب للموبايل','نموذج تواصل + واتساب','إعداد SEO أساسي','دعم النشر'],['إعداد وتخصيص المتجر','المنتجات والمجموعات والسلة','إعداد الدفع والشحن','تجربة مهيأة للموبايل','SEO وتحليلات أساسية'],['تصميم UI/UX مخصص','واجهة أمامية وخلفية','قاعدة بيانات وتسجيل دخول','ربط واجهات API','اختبار ونشر'],['تطوير متعدد المنصات','5–8 شاشات أساسية','ربط API والخلفية','تسجيل الدخول والإشعارات','دعم النشر على المتاجر'],['صفحة واحدة عالية التحويل','تصميم متجاوب','دعوة لاتخاذ إجراء + واتساب','تحسين السرعة','إعداد جاهز للتحليلات'],['تخطيط محتوى السوشيال ميديا','إعداد وتحسين الحملات','إعداد Meta Pixel والتتبع','تقارير الأداء','توصيات نمو شهرية']],ctas:['أنشئ موقعي','أنشئ متجري','أنشئ تطبيقي','أنشئ تطبيقي','أنشئ صفحة الهبوط','طوّر نشاطي'],note:'الأسعار مبدئية. الاستضافة والدومينات والتطبيقات المدفوعة والإنفاق الإعلاني والاشتراكات الخارجية منفصلة ما لم تُذكر ضمن العرض. يتم تحديد سعر المشروعات المخصصة بعد مراجعة المتطلبات.'},
    process:{eyebrow:'كيف أعمل',title:'عملية بسيطة. تواصل واضح. تسليم احترافي.',items:[['ناقش','نحدد أهدافك والمزايا والميزانية.'],['ابنِ','تصميم وتطوير مع تحديثات منتظمة.'],['أطلق','اختبار ونشر وتسليم المشروع.'],['طوّر','تسويق وتحسينات ودعم مستمر.']]},
    contact:{eyebrow:'جاهز للبدء؟',title:'أخبرني بما تريد إطلاقه.',text:'موقع أو تطبيق أو متجر إلكتروني أو حملة تسويقية — نحول الفكرة إلى منتج رقمي يعمل.',cta:'احصل على عرض مجاني'},
    footer:'© 2026 أحمد محي · مواقع · تطبيقات · تجارة إلكترونية · تسويق ·'
  };
  const AI={
    head:{'ai-sales-demo':['01 · وكيل مبيعات بالذكاء الاصطناعي','دع موقعك يبدأ محادثة المبيعات.','حوّل الزوار إلى فرص مؤهلة من خلال تجربة مبيعات تعمل دائمًا وتجيب عن الأسئلة وتفهم نية العميل وتقترح الخطوة التالية وتحول المحادثات المهمة إلى شخص حقيقي.','جرّب وكيل الذكاء الاصطناعي','شاهد مسار العمل'],'ai-services':['02 · الذكاء الاصطناعي والأتمتة','أكثر من مجرد شات بوت.','أنظمة ذكاء اصطناعي مصممة حول سير عمل حقيقي: جمع العملاء وتأهيلهم وتوجيههم وحجز المواعيد والدعم والمتابعة.'],'ai-workflow':['03 · مسار العمل من البداية للنهاية','من أول رسالة إلى تسليم المحادثة لشخص حقيقي.','النظام مبني حول رحلة واضحة بدلًا من صندوق دردشة عام.'],'ai-dashboard':['04 · ذكاء العملاء المحتملين','لوحة مبيعات مبنية حول المحادثة.','بيانات تجريبية فقط. يمكن استبدالها ببيانات CRM أو قاعدة بيانات حقيقية عند ربط النظام بسير عمل العميل.'],'ai-agent-playground':['05 · تجربة وكلاء الذكاء الاصطناعي','اختر نوع المحادثة.','بدّل شخصية التجربة لترى كيف يمكن تكييف نفس محرك المبيعات مع صناعات مختلفة.'],'ai-cases':['07 · دراسات الحالة','اعرض الأعمال كنظم أعمال متكاملة.','زوايا حقيقية لدراسات الحالة مبنية على المشاريع الموجودة بالفعل في هذا الموقع — بدون ادعاءات إيرادات غير حقيقية.'],'ai-roi':['08 · حاسبة العائد','احسب الفرصة قبل أن تبدأ الأتمتة.','استخدم أرقامك لمقارنة الإيرادات الشهرية الحالية مع معدل تحويل مستهدف توضيحي.'],'ai-pricing':['09 · حلول الذكاء الاصطناعي','باقات ذكاء اصطناعي يمكنك تقديمها للعملاء فعليًا.','يظل تسعير الذكاء الاصطناعي مخصصًا حتى تتضح التكاملات والاستخدام ومتطلبات الدعم.'],'ai-handoff':['10 · الإنسان + الذكاء الاصطناعي','الذكاء الاصطناعي يتولى الروتيني. والإنسان يتولى المهم.','النظام الموثوق يعرف متى يتوقف ويلخص السياق ويُدخل شخصًا حقيقيًا في المحادثة.'],'ai-language':['11 · العربية + الإنجليزية','مصمم لمحادثات العملاء ثنائية اللغة.','استخدم مفتاح اللغة بالأعلى لمعاينة كيفية تكييف تجربة الذكاء الاصطناعي وردوده للعملاء الناطقين بالعربية والإنجليزية.'],'ai-cta':['12 · ابدأ مشروع ذكاء اصطناعي','لا تكتفِ بعرض معرض أعمالك. دع الزوار يختبرون المنتج.','اطلب وكيل مبيعات بالذكاء الاصطناعي أو مساعد دعم العملاء أو مسار تأهيل العملاء أو لوحة تحكم أو نظام أتمتة مخصص.']},
    services:['وكيل مبيعات بالذكاء الاصطناعي','دعم العملاء بالذكاء الاصطناعي','تأهيل العملاء المحتملين','حجز المواعيد','مساعد المعرفة','أتمتة الأعمال'],
    serviceText:['تأهيل محادثي وتوجيه للمنتجات أو الخدمات والتعامل مع الاعتراضات واقتراح الخطوة التالية.','الإجابة عن الأسئلة الشائعة المعتمدة ومعرفة قاعدة المعلومات على مدار الساعة مع تحويل الحالات إلى شخص حقيقي عند الحاجة.','جمع التفاصيل المهمة وتقييم نية العميل وتوجيه الفرص عالية القيمة.','نقل العملاء المؤهلين إلى خطوة واضحة مثل عرض توضيحي أو استشارة أو اتصال.','إتاحة معلومات الشركة والمنتجات والمستندات المنظمة بسرعة للعملاء والفرق.','ربط النماذج وسجلات CRM والإشعارات وسير العمل المتكرر بحيث تنتقل المعلومات تلقائيًا.'],
    workflow:['زائر','محادثة','تأهيل','تقييم العميل','حجز / CRM','تسليم لشخص'],
    agents:[['وكيل التجارة الإلكترونية','المنتجات · التوصيات · إتمام الطلب'],['وكيل العقارات','المتطلبات · العقارات · المعاينات'],['وكيل اللياقة','التجارب · العضويات · الحجوزات'],['وكيل الضيافة','الأسئلة · الحجوزات · التوصيات'],['وكيل الاستشارات','الاحتياجات · التأهيل · الاستشارات']],
    cases:['تجارة إلكترونية','أزياء','تجارة فاخرة'],caseText:['استخدم المتجر كحالة تحويل: اكتشاف المنتجات وتجربة الموبايل ومسار أوضح من التصفح إلى الشراء.','أظهر كيف يمكن لسرد العلامة التجارية وعرض المنتجات والتجارة أن تعمل معًا في تجربة رقمية واحدة.','قدّم المشروع حول العرض الفاخر والتنقل الواضح وتجربة تسوق أقوى.'],
    handoff:[['الذكاء الاصطناعي يتولى','الأسئلة الشائعة والرد الأولي والتأهيل الأساسي واكتشاف المنتجات والمتابعة المتكررة.'],['متى يتم التصعيد','الطلبات المعقدة والمشكلات الحساسة وعدم وضوح النية والتفاوض أو طلب التحدث مع شخص.'],['ما يستلمه الموظف','بيانات العميل وملخص المحادثة ودرجة التأهيل والخطوة التالية المقترحة.']],
    prices:[['مساعد موقع بالذكاء الاصطناعي','عرض مخصص','للشركات التي تحتاج إلى طبقة ذكاء اصطناعي أولى مفيدة.',['مساعد قائم على المعرفة','جمع العملاء المحتملين','أتمتة الأسئلة الشائعة','تسليم لشخص'],'اطلب باقة البداية'],['وكيل مبيعات بالذكاء الاصطناعي','عرض مخصص','للشركات التي تريد مسارات التأهيل وحجز المواعيد.',['محادثات المبيعات','تقييم العملاء','مسار الحجز','تسليم جاهز للـCRM'],'اطلب باقة النمو'],['نظام أتمتة بالذكاء الاصطناعي','عرض مخصص','لسير العمل التجاري متعدد الخطوات والمتصل.',['عدة وكلاء','تكاملات API','لوحة تحكم مخصصة','تحسين مستمر'],'ناقش نظام الذكاء الاصطناعي المخصص']]
  };
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],text=(s,v)=>{const e=q(s);if(e)e.textContent=v},texts=(s,a)=>qa(s).forEach((e,i)=>{if(a[i]!=null)e.textContent=a[i]});
  function sync(){if((localStorage.getItem('lang')||'en')!=='ar')return;document.documentElement.lang='ar';document.documentElement.dir='rtl';document.body.classList.add('rtl');
    text('.header .eyebrow',AR.header.eyebrow);text('#title',AR.header.title);text('#subtitle',AR.header.subtitle);texts('.buttons a.chip',[AR.header.email,AR.header.whatsapp,AR.header.linkedin,AR.header.github,AR.header.instagram]);text('.hero-card .eyebrow',AR.build.eyebrow);text('.hero-card h2',AR.build.title);text('.hero-card p',AR.build.text);text('.hero-card .hero-cta',AR.build.cta);
    text('.work .section-heading .eyebrow',AR.work.eyebrow);text('#workTitle',AR.work.title);text('#workIntro',AR.work.intro);text('.pricing .section-heading .eyebrow',AR.pricing.eyebrow);text('#pricingTitle',AR.pricing.title);text('#pricingIntro',AR.pricing.intro);text('#pricingNote',AR.pricing.note);
    qa('.price-card').forEach((c,i)=>{const h=c.querySelector('h3'),p=c.querySelector('p'),a=c.querySelector('.price-cta'),l=c.querySelector('.price-label'),f=c.querySelector('.price span:first-child'),m=c.querySelector('.price span:last-child'),pop=c.querySelector('.popular');if(h)h.textContent=AR.pricing.titles[i];if(p)p.textContent=AR.pricing.desc[i];if(a)a.textContent=AR.pricing.ctas[i];if(l)l.textContent=AR.pricing.labels[i];if(f)f.textContent=AR.pricing.from;if(i===5&&m)m.textContent=AR.pricing.month;if(pop)pop.textContent=AR.pricing.popular;c.querySelectorAll('li').forEach((li,j)=>{if(AR.pricing.features[i]?.[j])li.textContent=AR.pricing.features[i][j]})});
    text('.process .eyebrow',AR.process.eyebrow);text('.process h2',AR.process.title);qa('.process-grid > div').forEach((e,i)=>{const s=e.querySelector('strong'),sp=e.querySelector('span');if(s)s.textContent=AR.process.items[i][0];if(sp)sp.textContent=AR.process.items[i][1]});text('.contact-card .eyebrow',AR.contact.eyebrow);text('.contact-card h2',AR.contact.title);text('.contact-card p',AR.contact.text);text('.contact-card .hero-cta',AR.contact.cta);
    const ftr=q('.footer');if(ftr){const email=ftr.querySelector('a');ftr.textContent=AR.footer+' ';if(email)ftr.appendChild(email)}
    qa('.work-card').forEach(c=>{const link=c.querySelector('.project-link');if(link)link.textContent=AR.work.enter;const preview=c.querySelector('.live-preview-wrap');if(preview){const s=preview.querySelector('.live-preview-overlay span'),a=preview.querySelector('.live-preview-overlay a'),fa=preview.querySelector('.live-preview-unavailable a'),fs=preview.querySelector('.live-preview-unavailable span');if(s)s.textContent=AR.work.snapshot;if(a)a.textContent=AR.work.open;if(fa)fa.textContent=AR.work.open;if(fs)fs.textContent='تعذر تحميل صورة المعاينة. الموقع الأصلي ما زال متاحًا.'} });
    text('.preview-header .eyebrow','الصفحة الرئيسية المباشرة');text('#previewTitle','معاينة المشروع');text('#previewExternal','فتح الموقع كاملًا ↗');text('#previewClose','إغلاق');text('#previewUrl','موقع مباشر');text('.preview-note','إذا كان الموقع يمنع المعاينة داخل الإطار، استخدم «فتح الموقع كاملًا ↗» لعرض الصفحة الرئيسية الأصلية في تبويب جديد.');syncAI();
  }
  function syncAI(){Object.entries(AI.head).forEach(([id,v])=>{if(!q('#'+id))return;if(id==='ai-sales-demo'){text('#ai-sales-demo .ai-panel:first-child .eyebrow',v[0]);text('#ai-sales-demo .ai-panel:first-child h2',v[1]);text('#ai-sales-demo .ai-panel:first-child p',v[2]);texts('#ai-sales-demo .ai-actions a',[v[3],v[4]]);text('#ai-sales-demo .ai-lang span','لغة التجربة');text('#ai-sales-demo .ai-chat-head .ai-status','● التجربة متصلة');text('#ai-sales-demo .ai-chat-head > span','تجربة توضيحية')}else{text('#'+id+' .ai-section-head .eyebrow',v[0]);text('#'+id+' .ai-section-head h2',v[1]);text('#'+id+' .ai-section-head p',v[2])}});
    texts('#ai-services .ai-feature h3',AI.services);texts('#ai-services .ai-feature p',AI.serviceText);texts('#ai-workflow .ai-step strong',AI.workflow);texts('#ai-agent-playground .agent-card strong',AI.agents.map(x=>x[0]));texts('#ai-agent-playground .agent-card > span:last-child',AI.agents.map(x=>x[1]));texts('#ai-cases .case-tag',AI.cases);texts('#ai-cases .case-card p',AI.caseText);texts('#ai-cases .case-link',['فتح المشروع ↗','فتح المشروع ↗','فتح المشروع ↗']);texts('#ai-dashboard .metric small',['المحادثات','المؤهلون','المواعيد','العملاء الساخنون','متوسط الرد','تغطية الذكاء الاصطناعي']);texts('#ai-dashboard .pipe-row span',['جديد','مؤهل','اجتماع','ساخن']);texts('#ai-dashboard .lead span',['علامة أزياء · تجارة إلكترونية','وكالة · أتمتة بالذكاء الاصطناعي','نشاط خدمي · موقع إلكتروني','شركة ناشئة · تطبيق ويب']);texts('#ai-dashboard .dash-title',['نظرة عامة على مبيعات الذكاء الاصطناعي · تجربة','مسار المبيعات','العملاء ذوو الأولوية']);
    const wa=q('#ai-whatsapp');if(wa){text('#ai-whatsapp .wa-head','أحمد AI · تجربة بأسلوب واتساب');texts('#ai-whatsapp .wa-bubble',['مرحبًا، أحتاج مساعدة للحصول على عملاء أكثر من موقعي.','بالتأكيد. ما نوع النشاط الذي تديره؟','لدي متجر أزياء. معظم الاستفسارات تصل بعد ساعات العمل.','أستطيع تأهيل هذه الاستفسارات على مدار الساعة وتوجيه العملاء ذوي النية العالية إلى فريقك.','هل يمكنني رؤية كيف سيعمل ذلك؟','نعم. ابدأ بتجربة الذكاء الاصطناعي بالأعلى أو اطلب مسار عمل مخصص.']);text('#ai-whatsapp .ai-copy .eyebrow','06 · تجربة متعددة القنوات');text('#ai-whatsapp .ai-copy h3','قابل العملاء حيث تحدث المحادثات بالفعل.');text('#ai-whatsapp .ai-copy p','يمكن تصميم نفس منطق التأهيل والدعم لمحادثات الموقع وتجارب شبيهة بواتساب والبريد الإلكتروني والقنوات المتصلة الأخرى. الواجهة هي الباب الأمامي فقط؛ أما سير العمل خلفها فهو ما يجعل النظام مفيدًا.');text('#ai-whatsapp .ai-copy a','ناقش مسار واتساب')}
    qa('#ai-pricing .ai-price').forEach((c,i)=>{const a=AI.prices[i];if(!a)return;const h=c.querySelector('h3'),v=c.querySelector('.ai-price-value'),p=c.querySelector('p'),l=c.querySelector('a'),tag=c.querySelector('.price-label');if(tag)tag.textContent=['بداية الذكاء الاصطناعي','نمو الذكاء الاصطناعي','ذكاء اصطناعي مخصص'][i];if(h)h.textContent=a[0];if(v)v.textContent=a[1];if(p)p.textContent=a[2];c.querySelectorAll('li').forEach((li,j)=>li.textContent=a[3][j]);if(l)l.textContent=a[4]});
    qa('#ai-handoff .handoff-card').forEach((c,i)=>{const a=AI.handoff[i];if(a){const s=c.querySelector('strong'),sp=c.querySelector('span');if(s)s.textContent=a[0];if(sp)sp.textContent=a[1]}});text('#aiLanguageTitle','مساعد واحد. لغتان. ونفس مسار المبيعات.');text('#aiLanguageText','تحافظ التجربة على نفس منطق التأهيل مع تغيير لغة المحادثة. ويمكن للنظام الحقيقي إضافة مصطلحات ونبرة ومعرفة معتمدة لكل سوق.');text('#aiChatInput','احكي للمساعد عن نشاطك...');text('#aiChatForm button','إرسال');texts('#ai-cta .ai-actions a',['ابدأ مشروع ذكاء اصطناعي','تحدث عبر واتساب']);
    text('#ai-roi .roi-result .eyebrow','الفرق الشهري التوضيحي');text('#ai-roi .roi-note','هذه حاسبة تخطيط وليست وعدًا بالنتائج. النتائج الفعلية تعتمد على جودة العملاء والعرض والزيارات وعملية المبيعات والتنفيذ.');texts('#ai-roi .roi-form label',['عدد العملاء المحتملين شهريًا','متوسط قيمة العميل (جنيه)','معدل التحويل الحالي %','معدل التحويل المستهدف %']);text('#roiCalculate','احسب الفرصة');const out=q('#roiOutput'),details=q('#roiDetails');if(out||details){const leads=Number(q('#roiLeads')?.value||0),value=Number(q('#roiValue')?.value||0),current=Number(q('#roiCurrent')?.value||0),target=Number(q('#roiTarget')?.value||0),diff=Math.max(0,leads*value*(target-current)/100),customers=Math.max(0,leads*(target-current)/100);if(out)out.textContent=`${Math.round(diff).toLocaleString('ar-EG')} جنيه`;if(details)details.textContent=`عند ${leads.toLocaleString('ar-EG')} عميل محتمل ومتوسط قيمة عميل ${value.toLocaleString('ar-EG')} جنيه، فإن الانتقال من معدل تحويل ${current}% إلى ${target}% يعني زيادة توضيحية قدرها ${customers.toLocaleString('ar-EG',{maximumFractionDigits:1})} عميل إضافي شهريًا.`}}
  const botMap={'I can prepare an AI package around your workflow. Tell me your business type and approximate monthly lead volume, then we can scope it.':'أستطيع إعداد باقة ذكاء اصطناعي مناسبة لسير عملك. أخبرني بنوع نشاطك وعدد العملاء المحتملين التقريبي شهريًا لنحدد النطاق المناسب.','For real estate, the agent can qualify buyers, capture requirements, recommend properties and move qualified prospects toward a viewing.':'في العقارات، يمكن للوكيل تأهيل المشترين وجمع متطلباتهم واقتراح العقارات المناسبة وتحويل العملاء المؤهلين إلى خطوة المعاينة.','For e-commerce, the agent can answer product questions, recommend items, recover buying intent and route high-value customers.':'في التجارة الإلكترونية، يمكن للوكيل الإجابة عن أسئلة المنتجات واقتراح العناصر واستعادة نية الشراء وتوجيه العملاء ذوي القيمة العالية.','A WhatsApp-style workflow can handle first response, qualification, FAQs, booking and human escalation.':'يمكن لمسار شبيه بواتساب التعامل مع الرد الأولي وتأهيل العملاء والأسئلة الشائعة والحجز وتحويل المحادثة إلى شخص حقيقي عند الحاجة.','Great. I would start by mapping your customer journey, qualification rules and the action you want the AI to complete after each conversation.':'ممتاز. سأبدأ بتحديد رحلة العميل وقواعد التأهيل والإجراء الذي تريد من الذكاء الاصطناعي تنفيذه بعد كل محادثة.'};
  const obs=new MutationObserver(()=>{if((localStorage.getItem('lang')||'en')==='ar')qa('#aiMessages .ai-msg.bot').forEach(m=>{const v=botMap[m.textContent.trim()];if(v)m.textContent=v})});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('languagechange',()=>setTimeout(sync,30));setTimeout(sync,100);
})();
