/* AI Growth Experience — interactive, client-safe demo layer. No API keys required. */
(function(){
  const section = (id, html) => { if(!document.getElementById(id)){ const el=document.createElement('section'); el.id=id; el.className='ai-growth'; el.innerHTML=html; document.querySelector('.hero-card')?.after(el); return el; } };

  const toast = (message) => { let t=document.querySelector('.ai-toast'); if(!t){t=document.createElement('div');t.className='ai-toast';document.body.appendChild(t)} t.textContent=message; t.classList.add('show'); clearTimeout(window.__aiToast); window.__aiToast=setTimeout(()=>t.classList.remove('show'),2600); };

  section('ai-sales-demo', `
    <div class="ai-hero">
      <div class="ai-panel">
        <div class="eyebrow">01 · AI SALES AGENT</div>
        <h2>Let your website start the sales conversation.</h2>
        <p>Turn visitors into qualified opportunities with an always-on AI sales experience that answers questions, understands intent, recommends the next step and hands high-value conversations to a human.</p>
        <div class="ai-actions"><a class="ai-primary" href="#ai-agent-playground">Try the AI Agent</a><a class="ai-secondary" href="#ai-workflow">See the workflow</a></div>
        <div class="ai-lang" style="margin-top:18px"><span style="font-size:9px;color:var(--muted)">Demo language</span><button class="active" data-ai-lang="en">EN</button><button data-ai-lang="ar">AR</button></div>
      </div>
      <div class="ai-panel ai-chat" aria-label="Interactive AI sales agent demo">
        <div class="ai-chat-head"><div><div class="ai-agent-name">Ahmed AI Sales Agent</div><div class="ai-status">● Demo online</div></div><span style="font-size:8px;color:var(--muted)">Illustrative demo</span></div>
        <div class="ai-messages" id="aiMessages"><div class="ai-msg bot" data-ai-en="Hi! I can help you choose the right digital solution. What are you trying to improve?" data-ai-ar="أهلاً! أقدر أساعدك تختار الحل الرقمي المناسب. إيه أكثر شيء عايز تطوره؟">Hi! I can help you choose the right digital solution. What are you trying to improve?</div></div>
        <form class="ai-chat-form" id="aiChatForm"><input id="aiChatInput" autocomplete="off" placeholder="Tell the agent about your business..." /><button type="submit">Send</button></form>
      </div>
    </div>`);

  section('ai-services', `
    <div class="ai-section-head"><div><div class="eyebrow">02 · AI & AUTOMATION</div><h2>More than a chatbot.</h2></div><p>AI systems designed around a real business workflow: capture, qualify, route, book, support and follow up.</p></div>
    <div class="ai-grid">
      <article class="ai-feature"><b>01</b><h3>AI Sales Agent</h3><p>Conversational qualification, product/service guidance, objection handling and next-step recommendations.</p></article>
      <article class="ai-feature"><b>02</b><h3>AI Customer Support</h3><p>Answers approved FAQs and knowledge-base questions around the clock, with human escalation when needed.</p></article>
      <article class="ai-feature"><b>03</b><h3>Lead Qualification</h3><p>Collect the few details that actually matter, score intent and route high-value opportunities.</p></article>
      <article class="ai-feature"><b>04</b><h3>Appointment Booking</h3><p>Move qualified prospects toward a clear next step such as a demo, consultation or callback.</p></article>
      <article class="ai-feature"><b>05</b><h3>Knowledge Assistant</h3><p>Give teams and customers fast access to structured company, product and document knowledge.</p></article>
      <article class="ai-feature"><b>06</b><h3>Business Automation</h3><p>Connect forms, CRM records, notifications and repetitive workflows so information moves automatically.</p></article>
    </div>`);

  section('ai-workflow', `
    <div class="ai-section-head"><div><div class="eyebrow">03 · END-TO-END WORKFLOW</div><h2>From first message to human handoff.</h2></div><p>The system is built around a clear journey instead of a generic chat box.</p></div>
    <div class="ai-workflow"><div class="ai-step"><span>01</span><strong>Visitor</strong></div><div class="ai-step"><span>02</span><strong>Conversation</strong></div><div class="ai-step"><span>03</span><strong>Qualification</strong></div><div class="ai-step"><span>04</span><strong>Lead Score</strong></div><div class="ai-step"><span>05</span><strong>Booking / CRM</strong></div><div class="ai-step"><span>06</span><strong>Human Handoff</strong></div></div>`);

  section('ai-dashboard', `
    <div class="ai-section-head"><div><div class="eyebrow">04 · LEAD INTELLIGENCE</div><h2>A sales dashboard built around the conversation.</h2></div><p>Demo data only. Replace with real CRM or database data when the system is connected to a client workflow.</p></div>
    <div class="ai-dashboard"><div class="dash-card"><div class="dash-title">AI Sales Overview · Demo</div><div class="metrics"><div class="metric"><small>Conversations</small><strong>48</strong></div><div class="metric"><small>Qualified</small><strong>14</strong></div><div class="metric"><small>Appointments</small><strong>8</strong></div><div class="metric"><small>Hot Leads</small><strong>5</strong></div><div class="metric"><small>Avg. Response</small><strong>&lt;1m</strong></div><div class="metric"><small>AI Coverage</small><strong>24/7</strong></div></div><div class="dash-title" style="margin-top:18px">Pipeline</div><div class="pipeline"><div class="pipe-row"><span>New</span><div class="pipe-bar"><i style="width:100%"></i></div><b>48</b></div><div class="pipe-row"><span>Qualified</span><div class="pipe-bar"><i style="width:58%"></i></div><b>14</b></div><div class="pipe-row"><span>Meeting</span><div class="pipe-bar"><i style="width:32%"></i></div><b>8</b></div><div class="pipe-row"><span>Hot</span><div class="pipe-bar"><i style="width:20%"></i></div><b>5</b></div></div></div><div class="dash-card"><div class="dash-title">Priority Leads</div><div class="score-list"><div class="lead"><span>Fashion brand · E-commerce</span><b>92/100</b></div><div class="lead"><span>Agency · AI automation</span><b>88/100</b></div><div class="lead"><span>Service business · Website</span><b>81/100</b></div><div class="lead"><span>Startup · Web app</span><b>76/100</b></div></div></div></div>`);

  section('ai-agent-playground', `
    <div class="ai-section-head"><div><div class="eyebrow">05 · AI AGENT PLAYGROUND</div><h2>Choose the conversation.</h2></div><p>Switch the demo persona to see how the same sales engine can be adapted to different industries.</p></div>
    <div class="ai-playground"><button class="agent-card active" data-agent="E-commerce"><span class="agent-icon">🛍️</span><strong>E-commerce Agent</strong><span>Products · recommendations · checkout</span></button><button class="agent-card" data-agent="Real Estate"><span class="agent-icon">🏠</span><strong>Real Estate Agent</strong><span>Requirements · properties · viewings</span></button><button class="agent-card" data-agent="Fitness"><span class="agent-icon">🏋️</span><strong>Fitness Agent</strong><span>Trials · memberships · bookings</span></button><button class="agent-card" data-agent="Hospitality"><span class="agent-icon">🏨</span><strong>Hospitality Agent</strong><span>Questions · bookings · recommendations</span></button><button class="agent-card" data-agent="Consultancy"><span class="agent-icon">💼</span><strong>Consultancy Agent</strong><span>Needs · qualification · consultations</span></button></div>`);

  section('ai-whatsapp', `
    <div class="ai-wa"><div class="wa-device"><div class="wa-head">Ahmed AI · WhatsApp-style demo</div><div class="wa-body"><div class="wa-bubble wa-in">Hi, I need help getting more customers from my website.</div><div class="wa-bubble wa-out">Absolutely. What type of business do you run?</div><div class="wa-bubble wa-in">A fashion store. Most of our enquiries arrive after working hours.</div><div class="wa-bubble wa-out">I can help qualify those enquiries 24/7 and route high-intent customers to your team.</div><div class="wa-bubble wa-in">Can I see how it would work?</div><div class="wa-bubble wa-out">Yes. Start with the AI demo above or request a custom workflow.</div></div></div><div class="ai-copy"><div class="eyebrow">06 · OMNICHANNEL EXPERIENCE</div><h3>Meet customers where conversations already happen.</h3><p>Design the same qualification and support logic for website chat, WhatsApp-style experiences, email and other connected channels. The interface is only the front door; the workflow behind it is what makes the system useful.</p><a class="ai-primary" href="https://wa.me/201016286261" target="_blank" rel="noopener noreferrer">Discuss a WhatsApp workflow</a></div></div>`);

  section('ai-cases', `
    <div class="ai-section-head"><div><div class="eyebrow">07 · CASE STUDIES</div><h2>Show the work as business systems.</h2></div><p>These are honest portfolio case-study angles based on the projects already shown on this website — no invented revenue claims.</p></div>
    <div class="ai-case-grid"><article class="case-card"><div class="case-tag">E-commerce</div><h3>LARO Cosmetics</h3><p>Use the storefront as a conversion case: product discovery, mobile UX and a cleaner path from browsing to purchase.</p><a class="case-link" href="https://laro-cosmetics.com/" target="_blank" rel="noopener noreferrer">Open project ↗</a></article><article class="case-card"><div class="case-tag">Fashion</div><h3>SWAY Maverick</h3><p>Show how brand storytelling, product presentation and commerce can work together in one digital experience.</p><a class="case-link" href="https://swaymaverick.com/" target="_blank" rel="noopener noreferrer">Open project ↗</a></article><article class="case-card"><div class="case-tag">Luxury commerce</div><h3>IRIS</h3><p>Position the project around premium presentation, clearer navigation and a stronger shopping journey.</p><a class="case-link" href="https://iriseg.net/" target="_blank" rel="noopener noreferrer">Open project ↗</a></article></div>`);

  section('ai-roi', `
    <div class="ai-section-head"><div><div class="eyebrow">08 · ROI CALCULATOR</div><h2>Model the opportunity before you automate.</h2></div><p>Use your own numbers to compare current monthly revenue with an illustrative target conversion rate.</p></div>
    <div class="ai-roi"><div class="roi-form"><label>Monthly leads<input id="roiLeads" type="number" min="0" value="100"></label><label>Average customer value (EGP)<input id="roiValue" type="number" min="0" value="2000"></label><label>Current conversion %<input id="roiCurrent" type="number" min="0" max="100" step="0.1" value="5"></label><label>Target conversion %<input id="roiTarget" type="number" min="0" max="100" step="0.1" value="8"></label><button class="ai-primary" id="roiCalculate" type="button">Calculate opportunity</button></div><div class="roi-result"><div class="eyebrow">Illustrative monthly difference</div><div class="roi-big" id="roiOutput">EGP 6,000</div><p id="roiDetails">At 100 leads and an EGP 2,000 average customer value, moving from 5% to 8% conversion represents an illustrative 3 additional customers per month.</p><p class="roi-note">This is a planning calculator, not a promise of results. Actual outcomes depend on lead quality, offer, traffic, sales process and implementation.</p></div></div>`);

  section('ai-pricing', `
    <div class="ai-section-head"><div><div class="eyebrow">09 · AI SOLUTIONS</div><h2>AI packages you can actually sell.</h2></div><p>Keep AI pricing custom until the exact integrations, usage and support requirements are known.</p></div>
    <div class="ai-pricing-grid"><article class="ai-price"><div class="price-label">AI STARTER</div><h3>AI Website Assistant</h3><div class="ai-price-value">Custom quote</div><p>For businesses that need a useful first AI layer.</p><ul><li>Knowledge-based assistant</li><li>Lead capture</li><li>FAQ automation</li><li>Human handoff</li></ul><a class="ai-secondary" href="mailto:ahmed171684@gmail.com?subject=AI%20Starter">Request AI Starter</a></article><article class="ai-price featured"><div class="price-label">AI GROWTH</div><h3>AI Sales Agent</h3><div class="ai-price-value">Custom quote</div><p>For businesses that want qualification and appointment workflows.</p><ul><li>Sales conversations</li><li>Lead scoring</li><li>Booking workflow</li><li>CRM-ready handoff</li></ul><a class="ai-primary" href="mailto:ahmed171684@gmail.com?subject=AI%20Sales%20Agent">Request AI Growth</a></article><article class="ai-price"><div class="price-label">AI CUSTOM</div><h3>AI Automation System</h3><div class="ai-price-value">Custom quote</div><p>For connected multi-step business workflows.</p><ul><li>Multiple agents</li><li>API integrations</li><li>Custom dashboard</li><li>Ongoing optimisation</li></ul><a class="ai-secondary" href="mailto:ahmed171684@gmail.com?subject=AI%20Custom">Discuss custom AI</a></article></div>`);

  section('ai-handoff', `
    <div class="ai-section-head"><div><div class="eyebrow">10 · HUMAN + AI</div><h2>AI handles the routine. Humans handle the important.</h2></div><p>A trustworthy system knows when to stop, summarize the context and bring a person into the conversation.</p></div>
    <div class="ai-handoff"><div class="handoff-card"><strong>AI handles</strong><span>FAQs, first response, basic qualification, product discovery and repetitive follow-up.</span></div><div class="handoff-card"><strong>Escalation trigger</strong><span>Complex requests, sensitive issues, unclear intent, negotiation or a direct request for a person.</span></div><div class="handoff-card"><strong>Human receives</strong><span>Lead details, conversation summary, qualification score and recommended next action.</span></div></div>`);

  section('ai-language', `
    <div class="ai-section-head"><div><div class="eyebrow">11 · ARABIC + ENGLISH</div><h2>Built for bilingual customer conversations.</h2></div><p>Use the language switch above to preview how the AI demo can adapt its interface and responses for Arabic-speaking and English-speaking customers.</p></div>
    <div class="ai-panel"><h3 id="aiLanguageTitle">One agent. Two languages. One consistent sales process.</h3><p id="aiLanguageText">The demo keeps the same qualification logic while changing the conversation language. A production implementation can add business terminology, tone and approved knowledge for each market.</p></div>`);

  section('ai-cta', `
    <div class="ai-panel"><div class="eyebrow">12 · START AN AI PROJECT</div><h2>Don't just show visitors your portfolio. Let them experience the product.</h2><p>Request an AI sales agent, customer-support assistant, lead qualification workflow, dashboard or custom automation system.</p><div class="ai-actions"><a class="ai-primary" href="mailto:ahmed171684@gmail.com?subject=AI%20Project%20Inquiry">Start an AI project</a><a class="ai-secondary" href="https://wa.me/201016286261" target="_blank" rel="noopener noreferrer">Talk on WhatsApp</a></div></div>`);

  function addBotMessage(text){const box=document.getElementById('aiMessages');if(!box)return;const div=document.createElement('div');div.className='ai-msg bot';div.textContent=text;box.appendChild(div);box.scrollTop=box.scrollHeight;}
  function handleChat(text){const t=text.toLowerCase();if(/price|cost|budget|سعر|تكلفة|ميزانية/.test(t)) return 'I can prepare an AI package around your workflow. Tell me your business type and approximate monthly lead volume, then we can scope it.';if(/real estate|عقار|عقارات/.test(t)) return 'For real estate, the agent can qualify buyers, capture requirements, recommend properties and move qualified prospects toward a viewing.';if(/shop|store|ecommerce|متجر|تجارة/.test(t)) return 'For e-commerce, the agent can answer product questions, recommend items, recover buying intent and route high-value customers.';if(/whatsapp|واتساب/.test(t)) return 'A WhatsApp-style workflow can handle first response, qualification, FAQs, booking and human escalation.';return 'Great. I would start by mapping your customer journey, qualification rules and the action you want the AI to complete after each conversation.';}
  document.getElementById('aiChatForm')?.addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('aiChatInput');const text=input.value.trim();if(!text)return;const box=document.getElementById('aiMessages');const u=document.createElement('div');u.className='ai-msg user';u.textContent=text;box.appendChild(u);input.value='';box.scrollTop=box.scrollHeight;setTimeout(()=>addBotMessage(handleChat(text)),350);});
  document.querySelectorAll('.agent-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.agent-card').forEach(c=>c.classList.remove('active'));card.classList.add('active');const type=card.dataset.agent;const input=document.getElementById('aiChatInput');if(input)input.placeholder=`Ask the ${type} about your business...`;addBotMessage(`The ${type} demo is ready. Tell me what you need and I’ll show the next step.`);}));
  function calculateROI(){const leads=Number(document.getElementById('roiLeads')?.value||0),value=Number(document.getElementById('roiValue')?.value||0),current=Number(document.getElementById('roiCurrent')?.value||0),target=Number(document.getElementById('roiTarget')?.value||0);const diff=Math.max(0,(leads*value*(target-current)/100));const customers=Math.max(0,leads*(target-current)/100);document.getElementById('roiOutput').textContent=`EGP ${Math.round(diff).toLocaleString()}`;document.getElementById('roiDetails').textContent=`At ${leads.toLocaleString()} leads and an EGP ${value.toLocaleString()} average customer value, moving from ${current}% to ${target}% conversion represents an illustrative ${customers.toFixed(1)} additional customers per month.`;}
  document.getElementById('roiCalculate')?.addEventListener('click',calculateROI);
  ['roiLeads','roiValue','roiCurrent','roiTarget'].forEach(id=>document.getElementById(id)?.addEventListener('input',calculateROI));

  const langCopy={en:{title:'One agent. Two languages. One consistent sales process.',text:'The demo keeps the same qualification logic while changing the conversation language. A production implementation can add business terminology, tone and approved knowledge for each market.',placeholder:'Tell the agent about your business...'},ar:{title:'مساعد واحد. لغتان. ونفس مسار المبيعات.',text:'التجربة تحافظ على نفس منطق التأهيل مع تغيير لغة المحادثة. ويمكن للنظام الحقيقي إضافة مصطلحات ونبرة ومعرفة معتمدة لكل سوق.',placeholder:'احكي للمساعد عن نشاطك...'}};
  function syncLang(){const lang=localStorage.getItem('lang')||'en';document.querySelectorAll('[data-ai-lang]').forEach(b=>b.classList.toggle('active',b.dataset.aiLang===lang));const c=langCopy[lang];const t=document.getElementById('aiLanguageTitle'),x=document.getElementById('aiLanguageText'),i=document.getElementById('aiChatInput');if(t)t.textContent=c.title;if(x)x.textContent=c.text;if(i)i.placeholder=c.placeholder;document.querySelectorAll('#aiMessages .ai-msg[data-ai-en]').forEach(m=>m.textContent=m.dataset[`ai${lang==='ar'?'Ar':'En'}`]);}
  document.querySelectorAll('[data-ai-lang]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem('lang',b.dataset.aiLang);syncLang();}));
  document.getElementById('langBtn')?.addEventListener('click',()=>setTimeout(syncLang,20));
  syncLang();
})();
