/* Centralized English/Arabic localization runtime for the existing static portfolio. */
(function () {
  "use strict";

  const ar = {
    "FREELANCE DIGITAL DEVELOPMENT · EGYPT":"تطوير رقمي مستقل · مصر",
    "Ahmed Mohy — Digital Products That Grow Businesses":"أحمد محي — منتجات رقمية تساعد الأعمال على النمو",
    "Websites · Web Applications · Online Stores · Mobile Apps · Digital Marketing":"مواقع إلكترونية · تطبيقات ويب · متاجر إلكترونية · تطبيقات موبايل · تسويق رقمي",
    "Email Me":"راسلني","WhatsApp":"واتساب","LinkedIn":"لينكدإن","GitHub":"جيت هب","Instagram":"إنستجرام",
    "WHAT I BUILD":"ماذا أبني","From idea to launch — websites, apps, stores and marketing.":"من الفكرة إلى الإطلاق — مواقع وتطبيقات ومتاجر وتسويق.",
    "Freelance digital solutions for startups, small businesses and growing brands. Clear pricing, modern design, responsive development and launch support.":"حلول رقمية مستقلة للشركات الناشئة والمشروعات الصغيرة والعلامات التجارية المتنامية. أسعار واضحة وتصميم حديث وتطوير متجاوب ودعم حتى الإطلاق.","Start Your Project":"ابدأ مشروعك",
    "SELECTED WORK":"أعمال مختارة","Real projects. Real interfaces. Built for real businesses.":"مشاريع حقيقية. واجهات حقيقية. مصممة لأعمال حقيقية.","Real live websites presented as current website snapshots. Open any project to enter the original site.":"مواقع حقيقية معروضة من خلال لقطات حديثة. افتح أي مشروع للدخول إلى الموقع الأصلي.","ENTER WEBSITE ↗":"دخول إلى الموقع ↗","LIVE WEBSITE SNAPSHOT":"لقطة مباشرة للموقع","OPEN WEBSITE ↗":"فتح الموقع ↗",
    "FREELANCER PRICING":"أسعار العمل المستقل","Professional work without agency-level pricing.":"عمل احترافي بدون أسعار وكالات مرتفعة.","Starting prices are designed to stay competitive for the Egyptian market while leaving room for custom features and higher-complexity projects.":"الأسعار المبدئية مصممة لتكون مناسبة للسوق المصري مع إمكانية إضافة المزايا المخصصة والمشروعات الأعلى تعقيدًا.","FROM":"ابتداءً من","/MONTH":"/شهريًا","MOST POPULAR":"الأكثر طلبًا",
    "Business Website":"موقع أعمال","For companies, freelancers, professionals and service businesses.":"للشركات والمستقلين والمحترفين ومقدمي الخدمات.","Build My Website":"أنشئ موقعي",
    "Online Store":"متجر إلكتروني","Professional Shopify or WooCommerce stores built for selling.":"متاجر Shopify أو WooCommerce احترافية مصممة للبيع.","Build My Store":"أنشئ متجري",
    "Web Application":"تطبيق ويب","Custom dashboards, booking systems, portals and business tools.":"لوحات تحكم وأنظمة حجز وبوابات وأدوات أعمال مخصصة.","Build My App":"أنشئ تطبيقي",
    "Mobile App MVP":"نسخة أولية لتطبيق موبايل","Lean Android & iOS MVPs for validating and launching an idea.":"تطبيقات Android وiOS عملية لاختبار الفكرة وإطلاقها.",
    "Campaign Landing Page":"صفحة هبوط لحملة","Fast, focused pages for products, services and advertising campaigns.":"صفحات سريعة ومركزة للمنتجات والخدمات والحملات الإعلانية.","Build My Landing Page":"أنشئ صفحة الهبوط",
    "Digital Marketing":"تسويق رقمي","Practical marketing support focused on visibility, leads and sales.":"دعم تسويقي عملي يركز على الظهور وجذب العملاء وزيادة المبيعات.","Grow My Business":"طوّر نشاطي",
    "Up to 5 pages":"حتى 5 صفحات","Responsive mobile design":"تصميم متجاوب للموبايل","Contact form + WhatsApp":"نموذج تواصل + واتساب","Basic SEO setup":"إعداد SEO أساسي","Deployment support":"دعم النشر",
    "Store setup & customization":"إعداد وتخصيص المتجر","Products, collections & cart":"المنتجات والمجموعات والسلة","Payment & shipping setup":"إعداد الدفع والشحن","Mobile-first UX":"تجربة مهيأة للموبايل","Basic SEO + analytics":"SEO وتحليلات أساسية",
    "Custom UI/UX":"تصميم UI/UX مخصص","Frontend + backend":"واجهة أمامية وخلفية","Database & authentication":"قاعدة بيانات وتسجيل دخول","API integrations":"ربط واجهات API","Deployment & testing":"اختبار ونشر",
    "Cross-platform development":"تطوير متعدد المنصات","5–8 core screens":"5–8 شاشات أساسية","API/backend integration":"ربط API والخلفية","Authentication & notifications":"تسجيل الدخول والإشعارات","Store publishing support":"دعم النشر على المتاجر",
    "Single high-converting page":"صفحة واحدة عالية التحويل","Responsive design":"تصميم متجاوب","CTA + WhatsApp/contact":"دعوة لاتخاذ إجراء + واتساب","Speed optimization":"تحسين السرعة","Analytics-ready setup":"إعداد جاهز للتحليلات",
    "Social media content planning":"تخطيط محتوى السوشيال ميديا","Campaign setup & optimization":"إعداد وتحسين الحملات","Meta Pixel / tracking setup":"إعداد Meta Pixel والتتبع","Performance reporting":"تقارير الأداء","Monthly growth recommendations":"توصيات نمو شهرية",
    "Prices are starting rates. Hosting, domains, paid apps, advertising spend and third-party subscriptions are separate unless included in the proposal. Custom projects are quoted after requirements review.":"الأسعار مبدئية. الاستضافة والدومينات والتطبيقات المدفوعة والإنفاق الإعلاني والاشتراكات الخارجية منفصلة ما لم تُذكر ضمن العرض. يتم تحديد سعر المشروعات المخصصة بعد مراجعة المتطلبات.",
    "HOW IT WORKS":"كيف أعمل","Simple process. Clear communication. Professional delivery.":"عملية بسيطة. تواصل واضح. تسليم احترافي.","Discuss":"ناقش","We define your goals, features and budget.":"نحدد أهدافك والمزايا والميزانية.","Build":"ابنِ","Design and development with regular updates.":"تصميم وتطوير مع تحديثات منتظمة.","Launch":"أطلق","Testing, deployment and handover.":"اختبار ونشر وتسليم المشروع.","Grow":"طوّر","Marketing, improvements and ongoing support.":"تسويق وتحسينات ودعم مستمر.",
    "READY TO BUILD?":"جاهز للبدء؟","Tell me what you want to launch.":"أخبرني بما تريد إطلاقه.","Website, application, online store or marketing campaign — let's turn the idea into a working digital product.":"موقع أو تطبيق أو متجر إلكتروني أو حملة تسويقية — نحول الفكرة إلى منتج رقمي يعمل.","Get a Free Quote":"احصل على عرض مجاني",
    "Project Preview":"معاينة المشروع","Open Full Site ↗":"فتح الموقع كاملًا ↗","Close":"إغلاق","Live website":"الموقع المباشر","LIVE HOMEPAGE":"الصفحة الرئيسية المباشرة","If a website blocks embedded previews, use Open Full Site ↗ to view the exact live homepage in a new tab.":"إذا منع أحد المواقع المعاينة داخل الصفحة، استخدم «فتح الموقع كاملًا ↗» لعرض الصفحة الرئيسية الأصلية في علامة تبويب جديدة.",

    "DIGITAL AGENCY WEBSITE":"موقع وكالة رقمية","SHOPIFY E-COMMERCE":"تجارة إلكترونية عبر Shopify","FASHION E-COMMERCE":"تجارة إلكترونية للأزياء","WOOCOMMERCE":"تجارة إلكترونية عبر WooCommerce","FASHION BRAND":"علامة أزياء","WEB DEVELOPMENT":"تطوير مواقع الويب","WEBSITE":"موقع إلكتروني","E-COMMERCE":"تجارة إلكترونية",
    "Modern agency website and digital brand presence with services, portfolio and contact experience.":"موقع وكالة حديث وحضور رقمي متكامل للعلامة التجارية، مع الخدمات ومعرض الأعمال وتجربة تواصل واضحة.",
    "Beauty e-commerce experience with product presentation and conversion-focused storefront UX.":"تجربة تجارة إلكترونية لمنتجات التجميل، مع عرض احترافي للمنتجات وتجربة متجر تركز على تحسين التحويلات.",
    "Modern fashion storefront designed for a clean and premium shopping experience.":"متجر أزياء حديث مصمم لتقديم تجربة تسوق نظيفة وراقية وسهلة الاستخدام.",
    "Quiet-luxury fashion presentation with refined product-focused UX.":"تجربة أزياء بطابع الفخامة الهادئة، مع واجهة راقية تركز على المنتجات وتجربة التسوق.",
    "Bold fashion e-commerce presentation built around strong product visuals.":"تجربة تجارة إلكترونية جريئة للأزياء مبنية حول عرض قوي للمنتجات وهوية بصرية واضحة.",
    "Business-focused web experience with a clear structure and modern interface.":"تجربة ويب موجهة للأعمال بهيكل واضح وواجهة حديثة وسهلة الاستخدام.",
    "Responsive digital experience designed around usability and clear content.":"تجربة رقمية متجاوبة مصممة حول سهولة الاستخدام وتقديم المحتوى بوضوح.",
    "Performance-minded website interface with a practical business-first layout.":"واجهة موقع تركز على الأداء وتقدم تخطيطًا عمليًا يضع احتياجات العمل في المقدمة.",
    "Premium product presentation focused on watches, trust and online shopping.":"عرض راقٍ للمنتجات يركز على الساعات وبناء الثقة وتجربة التسوق عبر الإنترنت.",

    "01 · AI SALES AGENT":"01 · وكيل مبيعات بالذكاء الاصطناعي","Let your website start the sales conversation.":"دع موقعك يبدأ محادثة المبيعات.","Turn visitors into qualified opportunities with an always-on AI sales experience that answers questions, understands intent, recommends the next step and hands high-value conversations to a human.":"حوّل الزوار إلى فرص مؤهلة من خلال تجربة مبيعات بالذكاء الاصطناعي تعمل باستمرار، وتجيب عن الأسئلة وتفهم النية وتقترح الخطوة التالية وتحول المحادثات المهمة إلى شخص حقيقي.","Try the AI Agent":"جرّب وكيل الذكاء الاصطناعي","See the workflow":"شاهد مسار العمل","Demo language":"لغة التجربة","Interactive AI sales agent demo":"تجربة تفاعلية لوكيل المبيعات بالذكاء الاصطناعي","Ahmed AI Sales Agent":"وكيل مبيعات أحمد بالذكاء الاصطناعي","● Demo online":"● التجربة متصلة","Illustrative demo":"تجربة توضيحية","Tell the agent about your business...":"احكِ للمساعد عن نشاطك...","Send":"إرسال",
    "02 · AI & AUTOMATION":"02 · الذكاء الاصطناعي والأتمتة","More than a chatbot.":"أكثر من مجرد روبوت محادثة.","AI systems designed around a real business workflow: capture, qualify, route, book, support and follow up.":"أنظمة ذكاء اصطناعي مصممة حول سير عمل حقيقي للأعمال: جمع البيانات والتأهيل والتوجيه والحجز والدعم والمتابعة.","AI Customer Support":"دعم عملاء بالذكاء الاصطناعي","Answers approved FAQs and knowledge-base questions around the clock, with human escalation when needed.":"الإجابة عن الأسئلة الشائعة المعتمدة وأسئلة قاعدة المعرفة على مدار الساعة مع التحويل إلى شخص عند الحاجة.","Lead Qualification":"تأهيل العملاء المحتملين","Collect the few details that actually matter, score intent and route high-value opportunities.":"جمع التفاصيل المهمة وتقييم نية العميل وتوجيه الفرص ذات القيمة العالية.","Appointment Booking":"حجز المواعيد","Move qualified prospects toward a clear next step such as a demo, consultation or callback.":"نقل العملاء المؤهلين إلى خطوة واضحة مثل تجربة أو استشارة أو مكالمة متابعة.","Knowledge Assistant":"مساعد المعرفة","Give teams and customers fast access to structured company, product and document knowledge.":"منح الفرق والعملاء وصولًا سريعًا إلى معرفة منظمة عن الشركة والمنتجات والمستندات.","Business Automation":"أتمتة الأعمال","Connect forms, CRM records, notifications and repetitive workflows so information moves automatically.":"ربط النماذج وسجلات CRM والإشعارات والمهام المتكررة بحيث تنتقل المعلومات تلقائيًا.","Conversational qualification, product/service guidance, objection handling and next-step recommendations.":"تأهيل العملاء عبر المحادثة وإرشادهم للمنتج أو الخدمة والتعامل مع الاعتراضات واقتراح الخطوة التالية.",
    "03 · END-TO-END WORKFLOW":"03 · مسار عمل متكامل","From first message to human handoff.":"من أول رسالة إلى التحويل لشخص حقيقي.","The system is built around a clear journey instead of a generic chat box.":"النظام مبني حول رحلة واضحة بدلًا من صندوق محادثة عام.","Visitor":"الزائر","Conversation":"المحادثة","Qualification":"التأهيل","Lead Score":"تقييم العميل المحتمل","Booking / CRM":"الحجز / CRM","Human Handoff":"التحويل لشخص",
    "04 · LEAD INTELLIGENCE":"04 · ذكاء العملاء المحتملين","A sales dashboard built around the conversation.":"لوحة مبيعات مبنية حول المحادثة.","Demo data only. Replace with real CRM or database data when the system is connected to a client workflow.":"بيانات تجريبية فقط. استبدلها ببيانات CRM أو قاعدة بيانات حقيقية عند ربط النظام بسير عمل العميل.","AI Sales Overview · Demo":"نظرة عامة على مبيعات الذكاء الاصطناعي · تجربة","Conversations":"المحادثات","Qualified":"مؤهلون","Appointments":"المواعيد","Hot Leads":"عملاء محتملون ساخنون","Avg. Response":"متوسط الاستجابة","AI Coverage":"تغطية الذكاء الاصطناعي","Pipeline":"مسار المبيعات","New":"جديد","Meeting":"اجتماع","Hot":"ساخن","Priority Leads":"العملاء ذوو الأولوية","Fashion brand · E-commerce":"علامة أزياء · تجارة إلكترونية","Agency · AI automation":"وكالة · أتمتة بالذكاء الاصطناعي","Service business · Website":"نشاط خدمي · موقع إلكتروني","Startup · Web app":"شركة ناشئة · تطبيق ويب",
    "05 · AI AGENT PLAYGROUND":"05 · تجربة وكلاء الذكاء الاصطناعي","Choose the conversation.":"اختر نوع المحادثة.","Switch the demo persona to see how the same sales engine can be adapted to different industries.":"بدّل شخصية التجربة لترى كيف يمكن تكييف محرك المبيعات نفسه مع مجالات مختلفة.","E-commerce Agent":"وكيل التجارة الإلكترونية","Products · recommendations · checkout":"المنتجات · التوصيات · الدفع","Real Estate Agent":"وكيل العقارات","Requirements · properties · viewings":"المتطلبات · العقارات · المعاينات","Fitness Agent":"وكيل اللياقة","Trials · memberships · bookings":"التجارب · العضويات · الحجوزات","Hospitality Agent":"وكيل الضيافة","Questions · bookings · recommendations":"الأسئلة · الحجوزات · التوصيات","Consultancy Agent":"وكيل الاستشارات","Needs · qualification · consultations":"الاحتياجات · التأهيل · الاستشارات",
    "06 · OMNICHANNEL EXPERIENCE":"06 · تجربة متعددة القنوات","Meet customers where conversations already happen.":"تواصل مع العملاء حيث تجري المحادثات بالفعل.","Design the same qualification and support logic for website chat, WhatsApp-style experiences, email and other connected channels. The interface is only the front door; the workflow behind it is what makes the system useful.":"صمّم نفس منطق التأهيل والدعم لمحادثة الموقع وتجارب شبيهة بواتساب والبريد الإلكتروني والقنوات المتصلة الأخرى. الواجهة هي الباب فقط؛ أما سير العمل خلفها فهو ما يجعل النظام مفيدًا.","Discuss a WhatsApp workflow":"ناقش سير عمل عبر واتساب",
    "07 · CASE STUDIES":"07 · دراسات حالة","Show the work as business systems.":"اعرض العمل كنظم أعمال متكاملة.","These are honest portfolio case-study angles based on the projects already shown on this website — no invented revenue claims.":"هذه زوايا واقعية لدراسات حالة مبنية على المشاريع المعروضة بالفعل في الموقع، دون ادعاءات إيرادات غير مثبتة.","E-commerce":"تجارة إلكترونية","Fashion":"أزياء","Luxury commerce":"تجارة فاخرة","Use the storefront as a conversion case: product discovery, mobile UX and a cleaner path from browsing to purchase.":"استخدم المتجر كحالة لتحسين التحويل: اكتشاف المنتجات وتجربة الموبايل ومسار أوضح من التصفح إلى الشراء.","Show how brand storytelling, product presentation and commerce can work together in one digital experience.":"وضّح كيف يمكن لقصة العلامة التجارية وعرض المنتجات والتجارة الإلكترونية أن تعمل معًا في تجربة رقمية واحدة.","Position the project around premium presentation, clearer navigation and a stronger shopping journey.":"قدّم المشروع حول العرض الراقي والتنقل الأوضح ورحلة التسوق الأقوى.","Open project ↗":"فتح المشروع ↗",
    "08 · ROI CALCULATOR":"08 · حاسبة العائد","Model the opportunity before you automate.":"قدّر الفرصة قبل أن تبدأ الأتمتة.","Use your own numbers to compare current monthly revenue with an illustrative target conversion rate.":"استخدم أرقامك لمقارنة الوضع الحالي شهريًا مع معدل تحويل مستهدف توضيحي.","Monthly leads":"العملاء المحتملون شهريًا","Average customer value (EGP)":"متوسط قيمة العميل (جنيه مصري)","Current conversion %":"معدل التحويل الحالي %","Target conversion %":"معدل التحويل المستهدف %","Calculate opportunity":"احسب الفرصة","Illustrative monthly difference":"الفرق الشهري التوضيحي","This is a planning calculator, not a promise of results. Actual outcomes depend on lead quality, offer, traffic, sales process and implementation.":"هذه حاسبة للتخطيط وليست وعدًا بالنتائج. تعتمد النتائج الفعلية على جودة العملاء المحتملين والعرض والزيارات وعملية البيع والتنفيذ.",
    "09 · AI SOLUTIONS":"09 · حلول الذكاء الاصطناعي","AI packages you can actually sell.":"حزم ذكاء اصطناعي قابلة للتطبيق والبيع فعليًا.","Keep AI pricing custom until the exact integrations, usage and support requirements are known.":"اجعل تسعير حلول الذكاء الاصطناعي مخصصًا حتى تتضح التكاملات والاستخدام ومتطلبات الدعم.","AI STARTER":"AI STARTER","AI Website Assistant":"مساعد موقع بالذكاء الاصطناعي","Custom quote":"عرض سعر مخصص","For businesses that need a useful first AI layer.":"للأعمال التي تحتاج إلى طبقة أولى مفيدة من الذكاء الاصطناعي.","Knowledge-based assistant":"مساعد قائم على المعرفة","Lead capture":"جمع العملاء المحتملين","FAQ automation":"أتمتة الأسئلة الشائعة","Human handoff":"تحويل لشخص","Request AI Starter":"اطلب AI Starter","AI GROWTH":"AI GROWTH","For businesses that want qualification and appointment workflows.":"للأعمال التي تريد مسارات لتأهيل العملاء وحجز المواعيد.","Sales conversations":"محادثات المبيعات","Lead scoring":"تقييم العملاء المحتملين","Booking workflow":"مسار الحجز","CRM-ready handoff":"تحويل جاهز لـ CRM","Request AI Growth":"اطلب AI Growth","AI CUSTOM":"AI CUSTOM","AI Automation System":"نظام أتمتة بالذكاء الاصطناعي","For connected multi-step business workflows.":"لسير عمل مترابط متعدد الخطوات للأعمال.","Multiple agents":"وكلاء متعددون","Custom dashboard":"لوحة تحكم مخصصة","Ongoing optimisation":"تحسين مستمر","Discuss custom AI":"ناقش حل ذكاء اصطناعي مخصص",
    "10 · HUMAN + AI":"10 · الإنسان + الذكاء الاصطناعي","AI handles the routine. Humans handle the important.":"الذكاء الاصطناعي يتولى الروتيني، والإنسان يتولى المهم.","A trustworthy system knows when to stop, summarize the context and bring a person into the conversation.":"النظام الموثوق يعرف متى يتوقف ويلخص السياق ويُدخل شخصًا حقيقيًا في المحادثة.","AI handles":"الذكاء الاصطناعي يتولى","FAQs, first response, basic qualification, product discovery and repetitive follow-up.":"الأسئلة الشائعة والاستجابة الأولى والتأهيل الأساسي واكتشاف المنتجات والمتابعة المتكررة.","Escalation trigger":"مؤشر التحويل","Complex requests, sensitive issues, unclear intent, negotiation or a direct request for a person.":"الطلبات المعقدة والمشكلات الحساسة وعدم وضوح النية والتفاوض أو طلب التحدث مع شخص مباشرة.","Human receives":"الشخص يستلم","Lead details, conversation summary, qualification score and recommended next action.":"بيانات العميل المحتمل وملخص المحادثة ودرجة التأهيل والخطوة التالية المقترحة.",
    "11 · ARABIC + ENGLISH":"11 · العربية + الإنجليزية","Built for bilingual customer conversations.":"مصمم لمحادثات العملاء باللغتين.","Use the language switch above to preview how the AI demo can adapt its interface and responses for Arabic-speaking and English-speaking customers.":"استخدم مفتاح اللغة بالأعلى لمعاينة كيفية تكييف واجهة واستجابات تجربة الذكاء الاصطناعي للعملاء الناطقين بالعربية والإنجليزية.","One agent. Two languages. One consistent sales process.":"مساعد واحد. لغتان. ومسار مبيعات متسق.","The demo keeps the same qualification logic while changing the conversation language. A production implementation can add business terminology, tone and approved knowledge for each market.":"تحافظ التجربة على نفس منطق التأهيل مع تغيير لغة المحادثة. ويمكن للتنفيذ الفعلي إضافة مصطلحات ونبرة ومعرفة معتمدة لكل سوق.",
    "12 · START AN AI PROJECT":"12 · ابدأ مشروع ذكاء اصطناعي","Don't just show visitors your portfolio. Let them experience the product.":"لا تكتفِ بعرض معرض أعمالك للزوار. دعهم يختبرون المنتج.","Request an AI sales agent, customer-support assistant, lead qualification workflow, dashboard or custom automation system.":"اطلب وكيل مبيعات بالذكاء الاصطناعي أو مساعد دعم عملاء أو مسار تأهيل أو لوحة تحكم أو نظام أتمتة مخصص.","Start an AI project":"ابدأ مشروع ذكاء اصطناعي","Talk on WhatsApp":"تحدث عبر واتساب"
  };

  const projects = {
    "We Wave Agency":["موقع وكالة رقمية","موقع وكالة حديث وحضور رقمي متكامل للعلامة التجارية، مع الخدمات ومعرض الأعمال وتجربة تواصل واضحة."],
    "LARO Cosmetics":["تجارة إلكترونية عبر Shopify","تجربة تجارة إلكترونية لمنتجات التجميل، مع عرض احترافي للمنتجات وتجربة متجر تركز على تحسين التحويلات."],
    "Saffa Fashion":["تجارة إلكترونية للأزياء","متجر أزياء حديث مصمم لتقديم تجربة تسوق نظيفة وراقية وسهلة الاستخدام."],
    "IRIS Contemporary Womenswear":["تجارة إلكترونية عبر WooCommerce","تجربة أزياء بطابع الفخامة الهادئة، مع واجهة راقية تركز على المنتجات وتجربة التسوق."],
    "SWAY Maverick":["علامة أزياء","تجربة تجارة إلكترونية جريئة للأزياء مبنية حول عرض قوي للمنتجات وهوية بصرية واضحة."],
    "ZREX":["تطوير مواقع الويب","تجربة ويب موجهة للأعمال بهيكل واضح وواجهة حديثة وسهلة الاستخدام."],
    "Ucypta":["موقع إلكتروني","تجربة رقمية متجاوبة مصممة حول سهولة الاستخدام وتقديم المحتوى بوضوح."],
    "Elprof10":["موقع إلكتروني","واجهة موقع تركز على الأداء وتقدم تخطيطًا عمليًا يضع احتياجات العمل في المقدمة."],
    "Royal Watch":["تجارة إلكترونية","عرض راقٍ للمنتجات يركز على الساعات وبناء الثقة وتجربة التسوق عبر الإنترنت."]
  };

  const lang = () => localStorage.getItem("lang") === "ar" ? "ar" : "en";
  const norm = (s) => String(s || "").replace(/\s+/g," ").trim();
  const original = (el, attr) => el.getAttribute(attr) || "";

  function rememberText(el) { if (!el.hasAttribute("data-i18n-source")) el.setAttribute("data-i18n-source", norm(el.textContent)); }
  function translateValue(source, locale) {
    if (locale === "en") return source;
    if (ar[source]) return ar[source];
    if (/^Open live (.+) homepage$/i.test(source)) return `فتح الصفحة الرئيسية المباشرة لـ ${source.match(/^Open live (.+) homepage$/i)[1]}`;
    if (/^Enter (.+) website$/i.test(source)) return `الدخول إلى موقع ${source.match(/^Enter (.+) website$/i)[1]}`;
    if (/^(.+) homepage preview$/i.test(source)) return `معاينة الصفحة الرئيسية لـ ${source.match(/^(.+) homepage preview$/i)[1]}`;
    if (/^(.+) website preview$/i.test(source)) return `معاينة موقع ${source.match(/^(.+) website preview$/i)[1]}`;
    if (/^(.+) live website preview$/i.test(source)) return `معاينة الموقع المباشر لـ ${source.match(/^(.+) live website preview$/i)[1]}`;
    if (/^Ask the (.+) about your business\.\.\.$/i.test(source)) return `اسأل وكيل ${source.match(/^Ask the (.+) about your business\.\.\.$/i)[1]} عن نشاطك...`;
    if (/^The (.+) demo is ready\. Tell me what you need and I’ll show the next step\.$/i.test(source)) return `تجربة ${source.match(/^The (.+) demo is ready/)[1]} جاهزة. أخبرني بما تحتاجه وسأوضح لك الخطوة التالية.`;
    return source;
  }

  function textNodes(root) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const result=[]; while(walker.nextNode()) result.push(walker.currentNode); return result;
  }

  function translateAttributes(root, locale) {
    ["aria-label","aria-description","alt","title","placeholder"].forEach((attr)=>root.querySelectorAll(`[${attr}]`).forEach((el)=>{
      if (el.tagName === "SCRIPT" || el.tagName === "STYLE") return;
      const key=`data-i18n-${attr}-source`; if(!el.hasAttribute(key)) el.setAttribute(key,norm(el.getAttribute(attr)));
      const source=original(el,key); if(source) el.setAttribute(attr,translateValue(source,locale));
    }));
  }

  function translateProjects(locale) {
    document.querySelectorAll(".work-card").forEach((card,index)=>{
      const title=norm(card.querySelector("h3")?.textContent); const key=Object.keys(projects).find((x)=>x.toLowerCase()===title.toLowerCase()); if(!key)return;
      const p=projects[key]; const label=card.querySelector(".project-topline span"); if(label)label.textContent=`${String(index+1).padStart(2,"0")} · ${locale==='ar'?p[0]:label.textContent.replace(/^\d+ · /,"")}`;
      const desc=card.querySelector(".work-info p"); if(desc){if(!desc.hasAttribute("data-i18n-project-en"))desc.setAttribute("data-i18n-project-en",norm(desc.textContent));desc.textContent=locale==='ar'?p[1]:desc.getAttribute("data-i18n-project-en");}
      const link=card.querySelector(".project-link"); if(link){link.textContent=locale==='ar'?"دخول إلى الموقع ↗":"ENTER WEBSITE ↗";link.setAttribute("aria-label",locale==='ar'?`الدخول إلى موقع ${key}`:`Enter ${key} website`);}
      const img=card.querySelector("img"); if(img)img.alt=locale==='ar'?`معاينة موقع ${key}`:`${key} website preview`;
    });
  }

  function translateMain(locale) {
    const set=(selector,value)=>{const el=document.querySelector(selector);if(el)el.textContent=value;};
    if(locale==='ar') {
      set(".header .eyebrow",ar["FREELANCE DIGITAL DEVELOPMENT · EGYPT"]);set("#title",ar["Ahmed Mohy — Digital Products That Grow Businesses"]);set("#subtitle",ar["Websites · Web Applications · Online Stores · Mobile Apps · Digital Marketing"]);
      const chips=["Email Me","WhatsApp","LinkedIn","GitHub","Instagram"];document.querySelectorAll(".buttons a.chip").forEach((el,i)=>{if(ar[chips[i]])el.textContent=ar[chips[i]];});
      set(".hero-card .eyebrow",ar["WHAT I BUILD"]);set(".hero-card h2",ar["From idea to launch — websites, apps, stores and marketing."]);set(".hero-card p",ar["Freelance digital solutions for startups, small businesses and growing brands. Clear pricing, modern design, responsive development and launch support."]);set(".hero-card .hero-cta",ar["Start Your Project"]);
      set(".work .section-heading .eyebrow",ar["SELECTED WORK"]);set("#workTitle",ar["Real projects. Real interfaces. Built for real businesses."]);set("#workIntro",ar["Real live websites presented as current website snapshots. Open any project to enter the original site."]);
      set(".pricing .section-heading .eyebrow",ar["FREELANCER PRICING"]);set("#pricingTitle",ar["Professional work without agency-level pricing."]);set("#pricingIntro",ar["Starting prices are designed to stay competitive for the Egyptian market while leaving room for custom features and higher-complexity projects."]);set("#pricingNote",ar["Prices are starting rates. Hosting, domains, paid apps, advertising spend and third-party subscriptions are separate unless included in the proposal. Custom projects are quoted after requirements review."]);
      document.querySelectorAll(".price-card").forEach((card)=>{card.querySelectorAll("span").forEach((s)=>{if(s.textContent.trim()==='FROM')s.textContent=ar.FROM;if(s.textContent.trim()==='/MONTH')s.textContent=ar['/MONTH'];});});
      set(".process .eyebrow",ar["HOW IT WORKS"]);set(".process h2",ar["Simple process. Clear communication. Professional delivery."]);[["Discuss","We define your goals, features and budget."],["Build","Design and development with regular updates."],["Launch","Testing, deployment and handover."],["Grow","Marketing, improvements and ongoing support."]].forEach((x,i)=>{const el=document.querySelectorAll(".process-grid>div")[i];if(el){el.querySelector("strong").textContent=ar[x[0]];el.querySelector("span").textContent=ar[x[1]];}});
      set(".contact-card .eyebrow",ar["READY TO BUILD?"]);set(".contact-card h2",ar["Tell me what you want to launch."]);set(".contact-card p",ar["Website, application, online store or marketing campaign — let's turn the idea into a working digital product."]);set(".contact-card .hero-cta",ar["Get a Free Quote"]);
      const footer=document.querySelector(".footer");if(footer){const email=footer.querySelector("a");footer.firstChild?.remove();footer.insertBefore(document.createTextNode("© 2026 أحمد محي · مواقع · تطبيقات · تجارة إلكترونية · تسويق · "),footer.firstChild);if(email)footer.appendChild(email);}
      set("#previewModal .eyebrow",ar["LIVE HOMEPAGE"]);set("#previewTitle",ar["Project Preview"]);set("#previewExternal",ar["Open Full Site ↗"]);set("#previewClose",ar["Close"]);set("#previewUrl",ar["Live website"]);set(".preview-note",ar["If a website blocks embedded previews, use Open Full Site ↗ to view the exact live homepage in a new tab."]);
    }
  }

  function metadata(locale){
    const title=locale==='ar'?"أحمد محي | مواقع · وكلاء ذكاء اصطناعي · تجارة إلكترونية · أتمتة":"Ahmed Mohy | Websites · AI Agents · E-commerce · Automation";
    const desc=locale==='ar'?"أحمد محي — تطوير المواقع ووكلاء المبيعات بالذكاء الاصطناعي وتطبيقات الويب والمتاجر الإلكترونية وتطبيقات الموبايل والتسويق الرقمي في مصر.":"Ahmed Mohy — Websites, AI sales agents, web applications, online stores, mobile apps and digital marketing in Egypt.";
    document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr';document.title=title;
    document.querySelector('meta[name="description"]')?.setAttribute('content',desc);document.querySelector('meta[property="og:locale"]')?.setAttribute('content',locale==='ar'?'ar_EG':'en_US');document.querySelector('meta[property="og:locale:alternate"]')?.setAttribute('content',locale==='ar'?'en_US':'ar_EG');
    let ogt=document.querySelector('meta[property="og:title"]');if(!ogt){ogt=document.createElement('meta');ogt.setAttribute('property','og:title');document.head.appendChild(ogt);}ogt.setAttribute('content',title);let ogd=document.querySelector('meta[property="og:description"]');if(!ogd){ogd=document.createElement('meta');ogd.setAttribute('property','og:description');document.head.appendChild(ogd);}ogd.setAttribute('content',desc);
  }

  function apply(){
    const locale=lang();metadata(locale);document.body.classList.toggle('rtl',locale==='ar');translateMain(locale);
    textNodes(document.body).forEach((node)=>{const parent=node.parentElement;if(!parent||['SCRIPT','STYLE','NOSCRIPT'].includes(parent.tagName))return;const value=norm(node.nodeValue);if(!value)return;if(!parent.hasAttribute('data-i18n-source'))parent.setAttribute('data-i18n-source',value);const source=parent.getAttribute('data-i18n-source');const translated=translateValue(source,locale);if(translated!==source||locale==='en'){const lead=node.nodeValue.match(/^\s*/)?.[0]||'';const trail=node.nodeValue.match(/\s*$/)?.[0]||'';node.nodeValue=lead+(locale==='ar'?translated:source)+trail;}});
    translateAttributes(document.body,locale);translateProjects(locale);const b=document.getElementById('langBtn');if(b)b.textContent=locale==='ar'?'EN':'AR';document.querySelectorAll('[data-ai-lang]').forEach((x)=>x.classList.toggle('active',x.dataset.aiLang===locale));
    document.body.setAttribute('data-locale',locale);
  }

  let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply();});};
  window.PortfolioI18n={getLocale:lang,setLocale:(l)=>{localStorage.setItem('lang',l==='ar'?'ar':'en');apply();},apply};
  const observer=new MutationObserver((records)=>{if(records.some((r)=>r.addedNodes.length))schedule();});observer.observe(document.body,{subtree:true,childList:true});
  document.addEventListener('click',(e)=>{const btn=e.target.closest('#langBtn,[data-ai-lang]');if(!btn)return;const next=btn.id==='langBtn'?(lang()==='ar'?'en':'ar'):btn.dataset.aiLang;setTimeout(()=>{localStorage.setItem('lang',next);apply();},0);});
  window.addEventListener('storage',(e)=>{if(e.key==='lang')apply();});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply,{once:true});else apply();
})();
